//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbmDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderItem
    {
        public int PurchaseOrderItemId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
